spring.application.name=courier_tracking_system

server.port=8080

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/CourierDB?useSSL=false 
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true 

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
